# 日期型转JSON
# 可以在属性上加@JsonFormat(timezon="GMT+8", pattern="yyyy-MM-dd") 或@JsonFormat(shape=JsonFormat.Shape.NUMBER)

spring:
  jackson:
    date-format: yyyy-MM-dd #如果使用字符串型表示，用这行设置格式
    timezone: GMT+8
    serialization:
      write-dates-as-timestamps: false #使用数值timestamp表示日期,优先级高于date-format,低于属性JsonFormat

# 日志级别：TRACE<DEBUG<INFO<ERROR<FATAL
logging:
  file: target/app.log
  level:
    ROOT: WARN
    top.fireguy: TRACE      
      
